# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Form.ui'
#
# Created: Sun Nov 30 05:33:58 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Admin_Form(object):
    def setupUi(self, Admin_Form):
        Admin_Form.setObjectName(_fromUtf8("Admin_Form"))
        Admin_Form.resize(470, 365)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403297645_User.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Admin_Form.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Admin_Form)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.workersComboBox = QtGui.QComboBox(self.centralwidget)
        self.workersComboBox.setObjectName(_fromUtf8("workersComboBox"))
        self.workersComboBox.addItem(_fromUtf8(""))
        self.workersComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.workersComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.workersTableWidget = QtGui.QTableWidget(self.centralwidget)
        self.workersTableWidget.setObjectName(_fromUtf8("workersTableWidget"))
        self.workersTableWidget.setColumnCount(4)
        self.workersTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.workersTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.workersTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.workersTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.workersTableWidget.setHorizontalHeaderItem(3, item)
        self.workersTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.horizontalLayout_5.addWidget(self.workersTableWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.refreshPushButton = QtGui.QPushButton(self.centralwidget)
        self.refreshPushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403548171_Synchronize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshPushButton.setIcon(icon1)
        self.refreshPushButton.setObjectName(_fromUtf8("refreshPushButton"))
        self.verticalLayout_2.addWidget(self.refreshPushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.exitPushButton = QtGui.QPushButton(self.centralwidget)
        self.exitPushButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403292146_Log Out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitPushButton.setIcon(icon2)
        self.exitPushButton.setObjectName(_fromUtf8("exitPushButton"))
        self.verticalLayout_2.addWidget(self.exitPushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.reportPushButton = QtGui.QPushButton(self.centralwidget)
        self.reportPushButton.setObjectName(_fromUtf8("reportPushButton"))
        self.horizontalLayout_4.addWidget(self.reportPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        Admin_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Admin_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        Admin_Form.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Admin_Form)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Admin_Form.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(Admin_Form)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(Admin_Form)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(Admin_Form)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Admin_Form)
        QtCore.QMetaObject.connectSlotsByName(Admin_Form)

    def retranslateUi(self, Admin_Form):
        Admin_Form.setWindowTitle(QtGui.QApplication.translate("Admin_Form", "Администратор", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Admin_Form", "Выберите работников: ", None, QtGui.QApplication.UnicodeUTF8))
        self.workersComboBox.setItemText(0, QtGui.QApplication.translate("Admin_Form", "Диспетчеры", None, QtGui.QApplication.UnicodeUTF8))
        self.workersComboBox.setItemText(1, QtGui.QApplication.translate("Admin_Form", "Заведующие гаражом", None, QtGui.QApplication.UnicodeUTF8))
        item = self.workersTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Admin_Form", "ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.workersTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Admin_Form", "ФИО", None, QtGui.QApplication.UnicodeUTF8))
        item = self.workersTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Admin_Form", "Зарплата", None, QtGui.QApplication.UnicodeUTF8))
        item = self.workersTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Admin_Form", "Оформлено поломок/выездов", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshPushButton.setToolTip(QtGui.QApplication.translate("Admin_Form", "<html><head/><body><p>Обновить записи</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exitPushButton.setToolTip(QtGui.QApplication.translate("Admin_Form", "<html><head/><body><p>Выход</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Admin_Form", "Сведения о пробеге автобуса: ", None, QtGui.QApplication.UnicodeUTF8))
        self.reportPushButton.setText(QtGui.QApplication.translate("Admin_Form", "Показать", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("Admin_Form", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("Admin_Form", "Действия", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("Admin_Form", "Обновить информацию", None, QtGui.QApplication.UnicodeUTF8))
        self.action_2.setText(QtGui.QApplication.translate("Admin_Form", "Показать статистику", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("Admin_Form", "Выход", None, QtGui.QApplication.UnicodeUTF8))

