# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditBreak_Form.ui'
#
# Created: Sun Nov 30 05:33:58 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EditBreak_Form(object):
    def setupUi(self, EditBreak_Form):
        EditBreak_Form.setObjectName(_fromUtf8("EditBreak_Form"))
        EditBreak_Form.resize(435, 420)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403292157_Edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EditBreak_Form.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(EditBreak_Form)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(EditBreak_Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.idSpinBox = QtGui.QSpinBox(EditBreak_Form)
        self.idSpinBox.setEnabled(True)
        self.idSpinBox.setMaximum(1000)
        self.idSpinBox.setObjectName(_fromUtf8("idSpinBox"))
        self.horizontalLayout_3.addWidget(self.idSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(EditBreak_Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.dateEdit = QtGui.QDateEdit(EditBreak_Form)
        self.dateEdit.setDate(QtCore.QDate(2014, 6, 13))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(EditBreak_Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.costsSpinBox = QtGui.QSpinBox(EditBreak_Form)
        self.costsSpinBox.setMaximum(1000000)
        self.costsSpinBox.setObjectName(_fromUtf8("costsSpinBox"))
        self.horizontalLayout.addWidget(self.costsSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(EditBreak_Form)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem3 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.busComboBox = QtGui.QComboBox(EditBreak_Form)
        self.busComboBox.setObjectName(_fromUtf8("busComboBox"))
        self.horizontalLayout_5.addWidget(self.busComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(EditBreak_Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.breaksWhatTextEdit = QtGui.QTextEdit(EditBreak_Form)
        self.breaksWhatTextEdit.setObjectName(_fromUtf8("breaksWhatTextEdit"))
        self.verticalLayout.addWidget(self.breaksWhatTextEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(EditBreak_Form)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.descriptionTextEdit = QtGui.QTextEdit(EditBreak_Form)
        self.descriptionTextEdit.setObjectName(_fromUtf8("descriptionTextEdit"))
        self.verticalLayout_3.addWidget(self.descriptionTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(EditBreak_Form)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.sparePartsTextEdit = QtGui.QTextEdit(EditBreak_Form)
        self.sparePartsTextEdit.setObjectName(_fromUtf8("sparePartsTextEdit"))
        self.verticalLayout_2.addWidget(self.sparePartsTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(EditBreak_Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.worksTextEdit = QtGui.QTextEdit(EditBreak_Form)
        self.worksTextEdit.setObjectName(_fromUtf8("worksTextEdit"))
        self.verticalLayout_4.addWidget(self.worksTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.cancelPushButton = QtGui.QPushButton(EditBreak_Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403362143_Cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelPushButton.setIcon(icon1)
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout_4.addWidget(self.cancelPushButton)
        self.okPushButton = QtGui.QPushButton(EditBreak_Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/1403362089_Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okPushButton.setIcon(icon2)
        self.okPushButton.setObjectName(_fromUtf8("okPushButton"))
        self.horizontalLayout_4.addWidget(self.okPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(EditBreak_Form)
        QtCore.QMetaObject.connectSlotsByName(EditBreak_Form)

    def retranslateUi(self, EditBreak_Form):
        EditBreak_Form.setWindowTitle(QtGui.QApplication.translate("EditBreak_Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EditBreak_Form", "ID поломки:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EditBreak_Form", "Дата поломки:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EditBreak_Form", "Затраты на ремонт:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EditBreak_Form", "Автобус:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EditBreak_Form", "Что сломалось:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EditBreak_Form", "Описание поломки:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EditBreak_Form", "Потребовавшиеся запчасти:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EditBreak_Form", "Проведенные работы:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("EditBreak_Form", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.okPushButton.setText(QtGui.QApplication.translate("EditBreak_Form", "OK", None, QtGui.QApplication.UnicodeUTF8))

